#!/bin/python3
##---------------------------------------------------------------------------------
## License: CC0-1.0 https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt
## Repository: https://github.com/LarsRockstroh/SwGuides/
## Filename: Fix_lcov.py
## Language: Python
## Description: Fixes path in info file generated by GHDL for genhtml from lcov
## History:
## 01.00, 2026-02-28
##   Initial
##---------------------------------------------------------------------------------

import os
with open("lcov.info") as f:
    newText=f.read().replace('SF:', 'SF:'+os.getcwd()+os.sep)

with open("lcov.info", "w") as f:
    f.write(newText)
